.env.sample, .github/actions/test/action.yml, .gitignore, Cargo.lock, Cargo.toml, Makefile, rust-toolchain, src/config.rs, src/main.rs, src/services/internal/didcomm_encrypted.rs, src/services/internal/didcomm_plaintext.rs, src/services/internal/didcomm_signed.rs, src/services/internal/mod.rs, src/services/nodex.rs
* Fix hard-code for endpoints
* Add dotenv
=> Add dotenv and refactoring hard-code

.github/CODEOWNERS
To maintain this repository and review by maintainers.
=> feat: Add codeowners

.env.sample, src/config.rs, src/main.rs, src/network.rs, src/nodex/utils/hub_client.rs, src/nodex/utils/mod.rs, src/services/hub.rs, src/services/mod.rs
```
$ cargo run -- --config network set --key secret_key --value test-secret
$ cargo run -- --config network get --key secret_key
$ cargo run -- --config network set --key project_id --value 01H5WG4Z07EHEF88159BSXV6SB
$ cargo run -- --config network get --key project_id
$ less ~/.config/nodex/network.json
{
"secret_key": "test-secret",
"project_id": "01H5WG4Z07EHEF88159BSXV6SB"
}
```
=> Add network json

Cargo.lock, Cargo.toml, examples/nodejs/package-lock.json, examples/nodejs/package.json, examples/nodejs/src/receive.ts, examples/nodejs/src/sock.ts, examples/nodejs/yarn.lock, src/controllers/public/mod.rs, src/controllers/public/nodex_receive.rs, src/main.rs, src/server.rs
Add `/receive` endpoint for receive message from Hub.
But, Hub endpoints are incomplete, so they are replaced by appropriate functions.
After launching NodeX Hub, run the following code
```shell
cargo run
yarn receive
```
<details> 
<summary> nodex log </summary>
```shell
2023-09-10T21:36:23 [INFO] - nodex_agent::controllers::public::nodex_receive - Receive message - src/controllers/public/nodex_receive.rs:62
2023-09-10T21:36:23 [INFO] - nodex_agent::handlers::receiver - stop receiver - src/handlers/receiver.rs:46
2023-09-10T21:36:28 [INFO] - nodex_agent::controllers::public::nodex_receive - Receive message - src/controllers/public/nodex_receive.rs:62
2023-09-10T21:36:32 [INFO] - nodex_agent::controllers::public::nodex_receive - Ok(HttpResponse { error: None, res: 
Response HTTP/1.1 101 …
```
=> Add receive endpoint

examples/nodejs/src/receive.ts, src/controllers/public/nodex_receive.rs, src/nodex/utils/hub_client.rs, src/services/hub.rs, src/services/internal/didcomm_encrypted.rs, src/services/internal/didcomm_plaintext.rs, src/services/internal/didcomm_signed.rs, src/services/internal/types.rs
The API `/receive` is for receiving messages from Hub. 
The User App receives the message through the endpoint `/receive` and notifies the Hub that it read the message via the WebSocket connection of the endpoint `/receive`.
I sent a message addressed to myself to the Hub to check that it worked.
1.  I rewrote the destination DID, and created DIDComm Encrypted message. 
```diff
diff --git a/examples/nodejs/src/generate_didcomm_encrypted_message.ts b/examples/nodejs/src/generate_didcomm_encrypted_message.ts
index e09f655..ba3d455 100644
--- a/examples/nodejs/src/generate_didcomm_encrypted_message.ts
+++ b/examples/nodejs/src/generate_didcomm_encrypted_message.ts
@@ -2,7 +2,7 @@ import { post } from './sock.js'
(async () => {
const json = await post('/internal/didcomm/encrypted-messages', { …
```
=> Implement the `/receive` Endpoint and add examples

src/controllers/public/nodex_receive.rs, src/handlers/heartbeat.rs, src/handlers/mod.rs, src/main.rs, src/nodex/utils/hub_client.rs, src/services/hub.rs
Create Agent heartbeat.
Run nodex agent and check mongodb with MongoDB Compass.
=> Implement heartbeat

Cargo.lock, Cargo.toml, src/controllers/public/nodex_transfer.rs, src/handlers/mod.rs, src/main.rs, src/nodex/utils/hub_client.rs, src/server.rs, src/services/hub.rs, src/services/nodex.rs
Create heartbeat api. 
Run example.
```
yarn transfer
```
=> Fix transfer client

Cargo.lock, Cargo.toml
Resolve release PR conflicts. So, import changes in the Main branch into the Develop branch..
And, I update the version for the 1.2.0 release.
=> Importing Master branch and bump version for release

examples/nodejs/src/network.ts, examples/nodejs/src/verify_didcomm_encrypted_message.ts, src/controllers/internal/network.rs, src/network.rs, src/nodex/utils/hub_client.rs, src/services/hub.rs
create update network.json api.
1. Run Hub and agent.
2. run example `network.ts`
=> Add update network json

src/controllers/public/nodex_receive.rs, src/nodex/schema/general.rs
Fix nodex_receive ResponseType because Device should receive VC.
=> fix: receive message type

.github/actions/publish/action.yml
=> (Re) release the `v1.2.1`

Cargo.lock, Cargo.toml
=> bump: cargo to v1.2.3

.github/actions/publish/action.yml, Cargo.lock, Cargo.toml, src/services/internal/didcomm_encrypted.rs, src/services/internal/didcomm_plaintext.rs, src/services/internal/didcomm_signed.rs
=> Release v1.2.3

.github/actions/check-team-affiliation-and-branch/action.yml
I tried to run a job to create a bump version of the PR.
https://github.com/nodecross/nodex/actions/runs/7692557159/job/20959654118
However, the actions had a grammatical error.
So we will fix it.
=> fix: add shell specification line

src/controllers/internal/did_generate_vc.rs, src/controllers/internal/didcomm_generate_encrypted.rs, src/controllers/internal/didcomm_generate_plaintext.rs, src/controllers/internal/didcomm_generate_signed.rs, src/nodex/utils/hub_client.rs, src/services/internal/did_vc.rs, src/services/internal/didcomm_encrypted.rs, src/services/internal/didcomm_plaintext.rs, src/services/internal/didcomm_signed.rs, src/services/nodex.rs
The date called 'issuance_date' was created in the function of DIDVCService.
To match the time used elsewhere, I changed it to allow passing the time from outside.
=> chore: add argument 'issuance_date' to DIDVCService

src/controllers/public/nodex_receive.rs
Increase polling interval from 5 sec to 1 hour
=> chore: Increase interval of polling

.github/actions/check-team-affiliation-and-branch/action.yml, .github/workflows/bump-version.yml, .releaserc.json, README.md
To release agent of version 1, I've changed the base branch and restrict action of bump version workflow.
=> chore: change base branch to release v1 binary

.github/actions/build-with-cross/action.yml, .github/actions/test/action.yml, .github/workflows/default-pipeline.yml, .github/workflows/release.yml, Cross.toml
=> chore: Build linux binary with cross for v1

.github/workflows/release.yml
=> chore: fix target of build linux job for v1

.github/actions/build-with-cross/action.yml
=> fix: change binary path and build target for v1 branch

.github/actions/build/action.yml
=> fix: Update upload artifact in build action for v1

src/controllers/internal/did_verify_vc.rs, src/controllers/internal/didcomm_generate_encrypted.rs, src/controllers/internal/didcomm_verify_encrypted.rs, src/controllers/public/nodex_create_verifiable_message.rs, src/controllers/public/nodex_receive.rs, src/controllers/public/nodex_verify_verifiable_message.rs, src/nodex/cipher/credential_signer.rs, src/nodex/runtime/secp256k1.rs, src/nodex/utils/hub_client.rs, src/services/hub.rs, src/services/internal/did_vc.rs, src/services/internal/didcomm_encrypted.rs, src/services/internal/didcomm_plaintext.rs, src/services/internal/didcomm_signed.rs, src/usecase/didcomm_message_usecase.rs, src/usecase/mod.rs, src/usecase/verifiable_message_usecase.rs
- Implement DidcommMessageUsecase to create `create_didcomm_message` / `verify_didcomm_message`.
- To test more easily, I refactored `DIDCommEncryptedService`
=> feat: implement DidcommMessageUsecase

Cargo.lock
Update some dependencies to avoid vulnerabilities.
=> chore: update packages in Cargo.lock

examples/nodejs/app/handler.ts, src/controllers/public/nodex_receive.rs, src/controllers/public/nodex_transfer.rs, src/nodex/utils/hub_client.rs, src/services/hub.rs
When transferring DIDComm message, metadata is not sent and received , so I fixed it.
↓Running example log
=> Bug fix about sending and receiving metadata for v1

Cargo.lock, Cargo.toml, e2e/Cargo.toml, src/main.rs, src/nodex/runtime/bip32.rs, src/nodex/runtime/secp256k1.rs
=> chore: Update libraries

examples/python/v2/cli/create_did.py, examples/python/v2/cli/find_did.py, examples/python/v2/cli/generate_didcomm_message.py, examples/python/v2/cli/sock.py, examples/python/v2/cli/verify_didcomm_message.py, examples/python/v2/cli/version_get.py, examples/python/v2/cli/verson_update.py
Create examples about below
- create_did
- find_did
- generate_didcomm_message
- verify_didcomm_message
- version_get
- version_update
=> Create examples implemented in TypeScript in Python

examples/python/v2/cli/create_did.py, examples/python/v2/cli/find_did.py, examples/python/v2/cli/generate_didcomm_message.py, examples/python/v2/cli/generate_vc_message.py, examples/python/v2/cli/requirements.txt, examples/python/v2/cli/sock.py, examples/python/v2/cli/verify_didcomm_message.py, examples/python/v2/cli/verify_vc_message.py, examples/python/v2/cli/version_get.py, examples/python/v2/cli/verson_update.py
About the python sample code,
- Not PEP8 compliant
- Standard output is difficult to read
- Formatted python example codes to be PEP8 compliant.
- Standard output made easier to read.
before
```
❯ python generate_didcomm_message.py                                                                                   
calling post http+unix://%2FUsers%2Fhirokiibuka%2F.nodex%2Frun%2Fnodex.sock:/create-didcomm-message
Traceback (most recent call last):
File "/Users/hirokiibuka/ghq/github.com/nodecross/nodex/examples/python/v2/cli/sock.py", line 26, in call
response.raise_for_status()
File "/Users/hirokiibuka/.asdf/installs/python/3.12.1/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: …
```
=> Format python example codes

examples/python/v2/cli/create_did.py, examples/python/v2/cli/find_did.py, examples/python/v2/cli/generate_didcomm_message.py, examples/python/v2/cli/generate_vc_message.py, examples/python/v2/cli/sock.py, examples/python/v2/cli/verify_didcomm_message.py, examples/python/v2/cli/verify_vc_message.py, examples/python/v2/cli/version_get.py, examples/python/v2/cli/verson_update.py
Expanded The refactor added in this PR to other examples.
https://github.com/nodecross/nodex/pull/284
In adittion, remove main function to simplify codes. (I think pros of definition main function is nothing for examples because there are no other functions)
=> Refactor example codes

src/main.rs, src/services/hub.rs
Added error handling to receive HTTP error codes added in the following two PRs.
https://github.com/nodecross/nodex-platform/pull/188
https://github.com/nodecross/nodex-platform/pull/185
=> Add error handling to /v1/device and /v1/device-info

.github/actions/build/action.yml, .github/workflows/default-pipeline.yml, test_resource/overrides/ubuntu-2304.yaml, test_resource/overrides/ubuntu-2404.yaml
- Add CI job to add toolchain (to fix failure on `x86_64-apple-darwin`)
- Change CI target from ubuntu-23.04 to ubuntu-24.04
=> Update CI test target image and Add toolchain

.env.sample, .github/actions/e2e/action.yml, src/config.rs, src/controllers/internal/network.rs, src/controllers/public/nodex_create_didcomm_message.rs, src/controllers/public/nodex_create_verifiable_message.rs, src/controllers/public/nodex_receive.rs, src/controllers/public/nodex_verify_didcomm_message.rs, src/controllers/public/nodex_verify_verifiable_message.rs, src/main.rs, src/nodex/utils/mod.rs, src/nodex/utils/studio_client.rs, src/services/mod.rs, src/services/studio.rs, test_resource/compose.yaml, test_resource/studio.yaml, test_resource/systemd/test.env
=> Rename "HUB" to "Studio"

src/config.rs, src/network.rs, src/services/studio.rs, test_resource/config/network.json
Rename hub_endpoint to studio_endpoint
=> Rename hub_endpoint to studio_endpoint

Cargo.lock, Cargo.toml, src/main.rs, src/repository/metric_repository.rs, src/repository/mod.rs, src/services/metrics.rs, src/services/mod.rs, src/services/studio.rs, src/usecase/metric_usecase.rs, src/usecase/mod.rs
Added process to retrieve Device metrics and send them to Studio's backend server.
=> [CGT-583] feat: get metrics

Cargo.lock, Cargo.toml
=> Release v2.0.1

.github/actions/e2e-with-docker/action.yml, .github/actions/e2e/action.yml, Cargo.lock, Cargo.toml, src/main.rs
Reverts nodecross/nodex#290
It may include bug.
At debian linux, `cargo run` is failed displaying "Terminated".
=> Revert "Chore/kill process when self update"

Cargo.lock, Cargo.toml
Merge after https://github.com/nodecross/nodex/pull/323, please.
=> update version to v2.0.2

examples/nodejs/src/getVersion.js, examples/python/src/get_version.py, src/server.rs
Change HTTP method of `get version` from POST to GET
=> Change HTTP method of get version

src/config.rs
Add metric interval validation
=> Add metric interval validation

.github/actions/lint/action.yml
=> chore: use taplo lint

.github/workflows/release.yml
Fixed windows release flow failed.
=> fix release windows

src/controllers/public/send_event.rs, src/repository/event_repository.rs, src/usecase/event_usecase.rs
- Add validation of event key and detail.
- Add studio error handling.
=> Add event validation

Cargo.lock, Cargo.toml
Release v2.2.1
Changes: https://github.com/nodecross/nodex/compare/v2.2.0...main
=> Release v2.2.1

examples/nodejs/src/generateAttribute.js, examples/python/src/generate_attribute.py, src/controllers/public/mod.rs, src/controllers/public/send_attributes.rs, src/repository/attribute_repository.rs, src/repository/mod.rs, src/server.rs, src/services/studio.rs, src/usecase/attribute_usecase.rs, src/usecase/mod.rs
=> Add attributes endpoint

examples/python/src/generate_custom_metric.py, examples/python/src/generate_event.py, examples/python/src/request.py
Add windows support that was omitted in the example
=> chore: support windows in python example

.github/workflows/bump-version.yml
=> Revert "Use GITHUB_TOKEN on bumv-version CI"

agent/src/controllers/internal/network.rs, agent/src/controllers/internal/version.rs, agent/src/controllers/public/mod.rs, agent/src/controllers/public/nodex_create_didcomm_message.rs, agent/src/controllers/public/nodex_create_identifier.rs, agent/src/controllers/public/nodex_create_verifiable_message.rs, agent/src/controllers/public/nodex_find_identifier.rs, agent/src/controllers/public/nodex_verify_didcomm_message.rs, agent/src/controllers/public/nodex_verify_verifiable_message.rs, agent/src/controllers/public/send_attribute.rs, agent/src/controllers/public/send_custom_metric.rs, agent/src/controllers/public/send_event.rs, agent/src/controllers/public/utils.rs, agent/src/errors.rs, agent/src/main.rs, agent/src/server.rs, examples/python/src/sock.py
Make the body of the error response into json
=> fix: Make the body of the error response into json

.github/workflows/bump-version.yml, Cargo.lock, protocol/Cargo.toml
Make protocol exclude from bumping.
=> fix: bump action

agent/src/controllers/public/send_custom_metric.rs, agent/src/repository/custom_metric_repository.rs, agent/src/services/studio.rs, agent/src/usecase/custom_metric_usecase.rs, examples/nodejs/src/generateCustomMetric.js, examples/python/src/generate_custom_metric.py
Make multiple custom metrics to be sent at once
=> [Breaking Change] feat: Make multiple custom metrics to be sent at once

.github/workflows/sign.yml
The file name of binary was wrong, so it has been corrected.
=> fix: bin name

.github/actions/build-preparation/action.yml, .github/actions/build-with-cross/action.yml, .github/actions/build-with-omnibus/action.yml, .github/actions/build/action.yml, .github/actions/lint/action.yml, .github/actions/test/action.yml
I have reduced the continuous integration time from 12 minutes to 7 minutes by utilizing the following build tools:
- mold (fast linker)
- sccache (cache build artifact)
=> chore: faster CI
