src/main.rs
Change rust log format
Before
```
warning: the following packages contain code that will be rejected by a future version of Rust: bigint v4.4.3, nom v5.1.2
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
Running `target/debug/nodex-agent`
[2023-05-24T08:13:10Z INFO  nodex_agent::nodex::extension::secure_keystore] Called: read_internal (type: Sign)
[2023-05-24T08:13:10Z INFO  nodex_agent::nodex::extension::secure_keystore] Called: read_internal (type: Update)
[2023-05-24T08:13:10Z INFO  nodex_agent::nodex::extension::secure_keystore] Called: read_internal (type: Recover)
[2023-05-24T08:13:10Z INFO  nodex_agent::nodex::extension::secure_keystore] Called: read_internal (type: Encrypt)
[2023-05-24T08:13:29Z …
```
=> Fix rust log format

Cargo.lock, Cargo.toml, src/main.rs, src/nodex/utils/hub_client.rs, src/services/hub.rs
=> Add send_device_info

src/main.rs, src/network.rs, src/services/hub.rs
`project_id` is the ID that should be only used in Hub. 
So, I removed `project_id` from network.json and added `project_did` alternatively.
Ensure that the word `project_id` does not exist in this repository.
```shell
nodex on  use-project-did [$!] via 🐳 desktop-linux is 📦 v1.1.12 via  v19.3.0 via 🦀 v1.70.0 via 🆂 on ☁️  (ap-northeast-1) 
❯ mdfind -onlyin . project_id
2023-09-19 01:43:52.292 mdfind[83034:34800141] [UserQueryParser] Loading keywords and predicates for locale "ja_JP"
2023-09-19 01:43:52.293 mdfind[83034:34800141] [UserQueryParser] Loading keywords and predicates for locale "ja"
```
=> Save ProjectDID in network.json

src/services/hub.rs
Currently, the error handle is not implemented and in any status code, the Agent will continue the process.
Therefore, I should fail and emit the error so that the executor can tell what failed.
=> feat: error handle status code for register device response

src/handlers/heartbeat.rs, src/nodex/utils/hub_client.rs, src/services/hub.rs
Because it should tell the server "when" the heartbeat event happened.
Currently, there is no information about it, and the server has to use the processing or etc.
=> feat: configure `event_at` for heart beat time

src/controllers/public/nodex_receive.rs, src/nodex/extension/secure_keystore.rs, src/services/internal/didcomm_encrypted.rs
Currently, there were insufficient logs to verify DIDComm.
Also, the key read log is being output at INFO level and other logs are being passed on, so we want to change the log level.
before
after
=> feat: Add log message to check verification steps.

.github/actions/publish/action.yml
Sorry, In the previous CI run [log](https://github.com/nodecross/nodex/actions/runs/6864576061/job/18667056390) the workflow failed, saying that the file doesn't exist. Thus, I'll fix this 🙏
=> Fix asset path for example release to use the relative path

.env.sample, src/config.rs
- Because we want to access the production Hub if we do not specify any environment variables
=> chore: Modify default value for NODEX_HUB_HTTP_ENDPOINT

Cargo.lock, Cargo.toml
We've forgotten to bump the version to this version in the latest release 🚀
=> chore: bump version to `v1.2.1`

examples/nodejs/app/README.md
The script (entry point of the command) is declared here:
https://github.com/nodecross/nodex/blob/05f2abd5142e4bfec91d0885293750c6ed8ee4e5/examples/nodejs/package.json#L14
The example documentation is wrong 😢
=> Fix entrypoint of the example app and make the installation command consistent with the documentation

Cargo.lock, Cargo.toml
=> bump: cargo to `v1.2.2`

.github/actions/publish/action.yml
Because the first argument is the file name... Sorry 🙏 
I messed up when I sorted it in my previous PR #206
=> fix: resort the example zip file entries and name the file `example.zip`

Cargo.lock, Cargo.toml, src/services/internal/didcomm_encrypted.rs, src/services/internal/didcomm_plaintext.rs, src/services/internal/didcomm_signed.rs
- Changed to fork the latest version of https://github.com/decentralized-identity/didcomm-rs because there was a bug in the 0.7.2 version.
- Since https://github.com/decentralized-identity/didcomm-rs is not maintaining the situation, we decided to maintain it at nodecross
- Because the logic of the DID format check was incorrect
- https://github.com/decentralized-identity/didcomm-rs/blob/main/src/messages/helpers/encryption.rs#L385C6-L400
main
```
[a-zA-Z0-9.\-_%]+    # method specific identifier
```
0.7.2
```
[a-zA-Z0-9]+    # method specific identifier
```
=> fix: change the version of forked version of didcomm-rs due to bugs in current version

.github/workflows/release.yml
- I redesigned the release workflow in this PR: https://github.com/nodecross/nodex/pull/217
- However, a mistake was made in uploading the examples.
=> fix: stop using the action `upload-release-asset`

src/nodex/extension/secure_keystore.rs, src/nodex/extension/trng.rs
The function `CStr::from_ptr` receives a pointer of `*const c_char`. The type `c_char` is depends on OS.
> On modern architectures this type will always be either [i8](https://doc.rust-lang.org/std/primitive.i8.html) or [u8](https://doc.rust-lang.org/std/primitive.u8.html), as they use byte-addresses memory with 8-bit bytes.
> https://doc.rust-lang.org/std/os/raw/type.c_char.html
In the MacOS environment, this code doesn't generate errors, but in linux it does.
I confirmed this by running ubuntu on an Apple silicon Mac.
Before running below command, I changed the example of the transfer to send message to itself.
```diff
diff --git a/examples/nodejs/cli/transfer.ts b/examples/nodejs/cli/transfer.ts
index 256aa05..38b1240 100644
--- a/examples/nodejs/cli/transfer.ts
+++ …
```
=> fix: ptr of CStr must use core::ffi::c_char

.github/actions/check-team-affiliation-and-branch/action.yml, .github/workflows/bump-version.yml, .github/workflows/release.yml
- Currently, We need to create the PR to update the version in Cargo.toml
- To reduce the operation, we want to automate it.
- I've added the new job to create PR to update the version in Cargo.toml
- To run only when a release is possible, the job is run after the Release job.
- https://github.com/nodecross/nodecross/issues/17
=> chore: add the job to create a pr to update the version of Cargo.toml

src/main.rs
Currently, the agent uses a proprietary format for logging time.
However, this has no time zone, making it difficult to match the time of log to the time of the message.
To solve this, use RFC3339 format which has a timezone information.
Before
```
2024-01-30T19:07:00 [ERROR] - nodex_agent::nodex::utils::hub_client - reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8000), path: "/v1/device", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })) } - src/nodex/utils/hub_client.rs:106
```
After
```
2024-01-30T19:01:52.239393+09:00 [ERROR] - …
```
=> chore: display log time in rfc3339

Cargo.lock, Cargo.toml, src/config.rs, src/nodex/extension/secure_keystore.rs, src/nodex/extension/trng.rs, src/nodex/keyring/keypair.rs, src/nodex/keyring/secp256k1.rs, src/nodex/runtime/aes_gcm_siv.rs, src/nodex/runtime/base64_url.rs, src/nodex/runtime/bip32.rs, src/nodex/runtime/hmac.rs, src/nodex/runtime/jcs.rs, src/nodex/runtime/multihash.rs, src/nodex/runtime/random.rs, src/nodex/runtime/secp256k1.rs
The error handling of nodex is too troublesome because of the error structure `NodeXError` has no information.
To simplify error handling, I've created some custom error types.
In this PR, the error type was changed by being used as a module.
I will try to change other `NodeXError` in the next PR.
=> feat: add custom error types for easy debugging

.github/workflows/bump-version.yml, .github/workflows/release.yml
We use the action [`get-user-teams-membership`](https://github.com/tspascoal/get-user-teams-membership) to check permission.
That action needs the permission to read GitHub teams. But, the default token of GitHub actions has no permission to read it. 
I've replaced the token to solve it.
To check whether the new token has a permission, I tried to run the job `Bump Version` on this branch.
https://github.com/nodecross/nodex/actions/runs/7766165527/job/21181693650
That job failed because it was run on a branch that was not the main branch, but passed the team affiliation check.
=> fix: change PAT for get-user-teams-memberships action

src/config.rs, src/controllers/public/nodex_receive.rs, src/handlers/heartbeat.rs, src/main.rs, src/network.rs, src/nodex/extension/secure_keystore.rs, src/nodex/extension/trng.rs, src/nodex/keyring/keypair.rs, src/nodex/utils/hub_client.rs, src/services/hub.rs
We provides the type `SingletonNetworkConfig` and `SingletonAppConfig`. However, the use of singleton object was not corrected.
To prevent initialization and ensure that only singleton objects can be used, I've moved some structs to packages and some public methods changed to private methods.
=> refactor: NetworkConfig and AppConfig must use singleton objects.

.github/workflows/bump-version.yml
I've tried to run the workflow "Bump Version", but it failed because of lack permission.
https://github.com/nodecross/nodex/actions/runs/7782139923/job/21217949516
I have modified my authorization to move workflow.
=> fix: change permission for bump version workflow

.github/workflows/bump-version.yml
I've succeeded to run the job 'Bump Version' and the job create this [PR](https://github.com/nodecross/nodex/pull/232).
But somehow that PR Commit was tied to my account.
I fixed it because the way I passed the github token was not good.
=> fix: rename input token for create-pull-request actions steps

Cargo.lock, Cargo.toml, src/controllers/public/nodex_receive.rs, src/handlers/mod.rs, src/nodex/errors/mod.rs, src/nodex/extension/trng.rs, src/nodex/mod.rs, src/nodex/runtime/random.rs, src/nodex/utils/http_client.rs, src/nodex/utils/hub_client.rs, src/services/hub.rs, src/services/internal/did_vc.rs, src/services/internal/did_vp.rs, src/services/internal/didcomm_encrypted.rs, src/services/internal/didcomm_plaintext.rs, src/services/internal/didcomm_signed.rs, src/services/nodex.rs
The original error type `NodeXError` has no information, so it is very difficult to debug errors.
NodeX is binary application, and it's suitable for using `anyhow::Error`.
I use custom errors with anyhow::error and thiserror as follows.
- `anyhow::Error`
- uses in binary application.
- uses when we don't need to use the method `downcast_ref' of `anyhow::Error`
- `thiserror::Error`
- uses in common modules. (e.g. cipher/extension/keyring/sidetree/runtime in nodex module.)
- uses when we want to handle differently in each error types in upper function.
You can now use anyhow::error in common modules. Because these modules are included in the nodex application package.
But I want to split packages to restrict using `anyhow::Error`.
I'll try to deal with this later.
=> refactor: Goodbye NodeXError. Welcome to anyhow::Error.

.github/actions/upload-release-asset/action.yml
I released nodex using the release workflow.
https://github.com/nodecross/nodex/actions/runs/7796128468
However, it failed because the input name for upload-release-asset was incorrect.
I changed the name from 'content_path' to 'asset_path' to fix this problem.
=> fix: rename input name in upload-release-asset action

src/nodex/extension/secure_keystore.rs
The deadlock was occurred in SecureKeyStore.
It's because SecureKeyStore::read/write has the lock, but SecureKeyStore::read_internal/write_internal wants to get the lock.
I ran the agent and tried to run a example 'yarn find_did'
```
2024-02-06T20:05:07.085070+09:00 [INFO] - nodex_agent - subscribed: nodex/did:nodex:test:EiCW6eklabBIrkTMHFpBln7574xmZlbMakWSCNtBWcunDg - src/main.rs:164
2024-02-06T20:05:07.085812+09:00 [INFO] - actix_server::builder - Starting 1 workers - /Users/rabe1028/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-server-2.1.1/src/builder.rs:200
2024-02-06T20:05:07.086160+09:00 [INFO] - nodex_agent::handlers::receiver - start receiver - src/handlers/receiver.rs:17
2024-02-06T20:05:07.086201+09:00 [INFO] - nodex_agent::handlers::sender - start sender - …
```
=> fix: deadlock in SecureKeyStore

.github/actions/test/action.yml, Cargo.lock, Cargo.toml, e2e/Cargo.toml, e2e/tests/test_verifiable_message.rs, src/controllers/public/mod.rs, src/controllers/public/nodex_create_verifiable_message.rs, src/controllers/public/nodex_verify_verifiable_message.rs, src/main.rs, src/network.rs, src/repository/did_repository.rs, src/server.rs, src/services/hub.rs, src/services/internal/did_vc.rs, src/services/internal/didcomm_encrypted.rs, src/services/internal/didcomm_signed.rs, src/services/nodex.rs, src/services/project_verifier.rs, src/usecase/verifiable_message_usecase.rs, test_resource/compose.yaml, test_resource/config/config.json, test_resource/config/network.json, test_resource/did_sidetree.yaml, test_resource/studio.yaml
- Implementation of a verifiable message api, except for sending message activities to Studio.
- Add e2e test scenario for a create-verifiable-message api and a verify-verifiable-message api.
- Add OpenAPI yaml to run mock server of NodeX Studio and SideTree.
- Add docker compose to run mock server.
You can check with following command.
```
curl -v --unix-socket ~/.nodex/run/nodex.sock \
-X POST \
-H "Content-Type: application/json" \
-d '{"message": "received from create api" }' \
http://localhost/verify-verifiable-message
```
Here is my result.
```
MESSAGE=$(curl --unix-socket ~/.nodex/run/nodex.sock \
-X POST \
-H "Content-Type: application/json" \
-d '{"destination_did" : "did:nodex:test:EiD_ZSrS4E4FZruAIJnMt1KjvH1HvwCRYdnIzYpQr4vsuQ" , "message" : "test"}' \ …
```
=> feat: Implement verify verifiable message

Cargo.lock, Cargo.toml, e2e/tests/test_verifiable_message.rs, src/controllers/public/nodex_create_verifiable_message.rs, src/controllers/public/nodex_verify_verifiable_message.rs, src/nodex/utils/hub_client.rs, src/repository/message_activity_repository.rs, src/repository/mod.rs, src/services/hub.rs, src/usecase/verifiable_message_usecase.rs, test_resource/studio.yaml
We want to send message activities to Studio when the api `create-verifiable-message` `verify-verifiable-message` called.
I also added a test case for UseCase failure.
- This is because these APIs in the studio are still being implemented.
=> feat: send message activities to studio

.github/actions/build-with-cross/action.yml, .github/actions/test/action.yml, .github/workflows/default-pipeline.yml, .github/workflows/release.yml, Cross.toml
Currently, the linux binary built in the workflow on ubuntu-latest runner.
However, that OS has a high version of glibc, which creates binaries that do not work on some OS.
To fix this problem, we use cross to build binary in docker image `ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main-centos`.
That centos docker image uses glibc 2.17.
https://github.com/cross-rs/cross
=> chore: build linux binary using cross

.github/workflows/release.yml
I made a mistake with the target value for the `build-linux` job.
=> chore: fix target in build-linux job

.github/actions/build-with-cross/action.yml
The binary build in linux isn't uploaded when I checked this job.
https://github.com/nodecross/nodex/actions/runs/7941176716/job/21683246445
This was due to an incorrect target name in the `build-with-cross` step and an incorrect binary path.
I've checked the job result.
https://github.com/nodecross/nodex/actions/runs/7941404537/job/21683720004
=> fix: change binary path and build target

.github/actions/build/action.yml
The third party action `download-artifact@v4` can download assets uploaded using `upload-artifact@v4`.
I've update the version of that action.
=> fix: update upload-artifact and tiny refactoring

e2e/tests/test_didcomm_message.rs, src/controllers/public/mod.rs, src/controllers/public/nodex_create_didcomm_message.rs, src/controllers/public/nodex_verify_didcomm_message.rs, src/server.rs, src/services/internal/didcomm_encrypted.rs, src/usecase/didcomm_message_usecase.rs
Implement apis `create_didcomm_message` and `verify_didcomm_message`.
You can check with following command.
```
curl --unix-socket ~/.nodex/run/nodex.sock \
-X POST \
-H "Content-Type: application/json" \
-d '{"destination_did" : "did:nodex:test:your-own-did" , "operation_tag": "didcomm", "message" : "test"}' \
http://localhost/create-didcomm-message
curl -v --unix-socket ~/.nodex/run/nodex.sock \
-X POST \
-H "Content-Type: application/json" \
-d '{"message": "received from create api" }' \
http://localhost/verify-didcomm-message
```
Here is my result.
```
MESSAGE=$(curl --unix-socket ~/.nodex/run/nodex.sock \
-X POST \
-H "Content-Type: application/json" \
-d '{"destination_did" : "did:nodex:test:EiDEp_0NuvczSI9n-8B5NmQoBQX__QORK-uZOhRs2zc_6A" , "operation_tag": "didcomm", "message" : …
```
=> feat: implement create/verify didcomm message apis

.github/workflows/release.yml
Because cli examples are needed.
=> fix: add cli to example zip

.github/workflows/release.yml
Release Assets Release Body and zipped code were created from the main branch.
https://github.com/nodecross/nodex/releases/tag/v1.2.6
This is because the `target_commitish` argument was not specified when calling the github api.
=> chore: specify `target_commitish` when create a release

.github/workflows/default-pipeline.yml
- https://github.com/actions/runner/issues/1456 was resolved.
- The job `e2e-macos` is too heavy, so I increased that timeout minutes.
=> chore: fix CI jobs on MacOS

e2e/tests/test_didcomm_message.rs, e2e/tests/test_verifiable_message.rs, src/controllers/public/nodex_verify_didcomm_message.rs, src/controllers/public/nodex_verify_verifiable_message.rs, src/usecase/didcomm_message_usecase.rs, src/usecase/verifiable_message_usecase.rs
When DIDComm message verify, user application cannot know VC, so verify result should be VC.
When verifying VC, the result is also adjusted to DIDComm.
<details>
<summary> result of verify_didcomm_message.py </summary>
```
{
"issuer": {
"id": "$DID"
},
"issuanceDate": "2024-03-17T06:31:47.335224+00:00",
"@context": [
"https://www.w3.org/2018/credentials/v1"
],
"type": [
"VerifiableCredential"
],
"credentialSubject": {
"container": {
"created_at": "2024-03-17T06:31:47.335224+00:00",
"message_id": "5a6a2d89-7b19-4be7-9787-5c099929d8de",
"payload": "{\"string\": \"value\",\"number\": 1,\"boolean\": true,\"array\": [],\"map\": {}}",
"project_hmac": ""
}
},
"proof": {
"type": "EcdsaSecp256k1Signature2019",
"proofPurpose": "authentication",
"created": "2024-03-17T06:31:47.364811+00:00", …
```
=> fix: change verify response type to VC

src/services/hub.rs, test_resource/studio.yaml
Fix URL of the message activity endpoint.
`/v1/message_activity` -> `/v1/message-activity`
Teted at my local development environment, with fixed server app.
=> /v1/message_activity -> /v1/message-activity

examples/python/v2/cli/generate_vc_message.py, examples/python/v2/cli/verify_vc_message.py
The current `verify_vc_message.py` has the following issues.
- The JSON (payload) in the JSON must have two backslashes. The output of `generate_vc_message.py` has only one backslash, so the user must modify it to two to copy it and paste.
Define individual JSON objects as python objects instead of the entire payload as a string.
In addition, the following fixes were made.
- Made explicit where the user has to modify
- Refactored the entire code
- made the output clearer
example
```
❯ python generate_vc_message.py                                                                                                                                                                                                                                 03/22 20:42:53
Now Requesting...
- Method: POST
- URL: …
```
=> Refactor example codes of vc

src/controllers/public/nodex_create_didcomm_message.rs, src/controllers/public/nodex_verify_didcomm_message.rs, src/repository/message_activity_repository.rs, src/services/hub.rs, src/usecase/didcomm_message_usecase.rs, src/usecase/verifiable_message_usecase.rs
Difficult to troubleshoot due to lack of handling of HTTP errors in HUB.
Add HTTP error handling of POST and PUT message activity.
Confirmed that python test code can catch error status and message.
=> Add HTTP error handling of message activity endpoint

src/controllers/public/nodex_create_verifiable_message.rs, src/controllers/public/nodex_verify_verifiable_message.rs, src/usecase/verifiable_message_usecase.rs
Expanded implimentation of error handling added in this PR to the handlers of VC Message.
https://github.com/nodecross/nodex/pull/281
1. generate vc message by example code.
2. delete vc message from DB.
3. verify vc message by example code.
4. the result is below.
```
❯ python verify_vc_message.py                                   
Now Requesting...
- Method: POST
- URL: http+unix:///Users/hirokiibuka/.nodex/run/nodex.sock:/verify-verifiable-message
The response is as follows.
404 Not Found "Message Activity ID not found"
```
=> Add error handling to handlers of VC message

Cargo.lock, Cargo.toml, examples/python/v2/cli/version_update.py, src/main.rs, src/services/nodex.rs
When run on Debian, the process terminates and crashes, displaying "terminated".
This was done because the process works fine on macOS and Windows. The problem was due to clone3 being issued multiple times when running the process on Debian, so the process was dropped with terminated at runtime.
The changes include
- Changed to skip processes with the same parent PID
- Changed to make the parent process different by deamonize at the point where it is started by spawn
- Fixed a flaw in example
=> fix kill other processes

.github/actions/e2e-with-docker/action.yml, .github/actions/e2e/action.yml, .github/workflows/default-pipeline.yml, src/services/studio.rs, test_resource/compose.yaml, test_resource/studio.yaml
Fixed problem with e2e test crashing
=> fix e2e test

.github/workflows/release.yml
In previous versions, nodejs example was zipped as the target, but the directory structure has changed and python has been added.
We have adapted to those changes.
=> fix zip example on release flow

src/config.rs
Since hex::encode is also executed in the to_hex_key_pair, there is no need to encode at the modified location.
=> fix to_keypair_config

src/controllers/public/send_custom_metric.rs, src/repository/custom_metric_repository.rs, src/repository/event_repository.rs, src/usecase/custom_metric_usecase.rs, src/usecase/event_usecase.rs
Return 400 error when key is an empty string
```
~/r/c/nodex   feature/custom-metrics-key-validation *$…  examples/python  ./venv/bin/python src/generate_custom_metric.py
Now Requesting...
- Method: POST
- URL: http+unix:///Users/xxx/.nodex/run/nodex.sock:/custom_metrics
The response is as follows.
400 Bad Request "key is required"
```
=> Add validation to custom_metrics

Cargo.lock, Cargo.toml
- rustls does not use OS CA Cert.
- This causes inconvenience when using https proxy with ssl bump.
- Users must add CA Cert manually.
- Make rustls use OS CA Cert.
- There is test with proxy. 
- https://github.com/nodecross/nodex/tree/feat/proxy-test/test_resource/vagrant
-  Not tested on macOS.
=> fix: use OS CA certificate

src/usecase/metric_usecase.rs
=> Fix: Send metrics typo logging

.github/actions/lint/action.yml
Make the installation of taplo-cli faster using the taiki-e/install-action action, which utilizes cargo binstall.
=> chore: faster installation for taplo

.github/actions/test/action.yml
Discontinued sending test coverage to Coveralls and modified test execution to use cargo-nextest.
=> fix: remove coveralls and use cargo-nextest

agent/src/repository/metric_repository.rs, agent/src/services/studio.rs
During NodeX Studio's maintenance mode, the NodeX agent caches metrics in a VecDeque structure.
Once NodeX Studio becomes available again, the agent resumes sending these cached metrics.
However, there's a potential issue where the agent's cache size may exceed the maximum allowable size for JSON requests to NodeX Studio.
To address this, this PR implements a solution that creates size-limited JSON request chunks.
This approach ensures that all metrics are successfully transmitted, regardless of the cache size, by breaking down large data sets into manageable portions.
=> feat: implement size-limited JSON requests for save metrics

agent/src/controllers/public/send_custom_metric.rs, agent/src/controllers/public/send_event.rs, agent/src/controllers/public/utils.rs, agent/src/server.rs, agent/src/services/studio.rs, examples/nodejs/src/generateCustomMetric.js, examples/nodejs/src/generateEvent.js, examples/python/src/generate_custom_metric.py, examples/python/src/generate_event.py
Make `occurred_at` to be specified as a 13-digit timestamp
=> feat: Make "occurred_at" to be specified as a 13-digit timestamp

.github/workflows/sign.yml
This is a verification workflow for implementing signature verification.
It actually signs the binary by cosign and outputs the generated bundle and binary.
=> feat: sign on workflow dispatch for verification

agent/src/controllers/public/nodex_find_identifier.rs
localhost%3A8000:webvh:v1:uuid などのDID パスが渡された際にaxum の方で解釈が入ってしまい, localhost:8000:webvh:v1:uuid という形式になるため後続のDID のパス変換処理で不具合が生じるためuri からPath を抽出する方法に改修した
=> refactor: update nodex find identifier handler to use Uri
